---
chunk_id: discourse_topic_164277_post_517_00
source_url: https://discourse.onlinedegree.iitm.ac.in/t/164277/517
source_title: Project 1 - LLM-based Automation Agent - Discussion Thread [TDS Jan 2025]
content_type: discourse
tokens: 214
username: 23f3002091
post_number: 517
topic_id: 164277
---

## Post #517 by 23f3002091

**Direct Link**: [Post #517](https://discourse.onlinedegree.iitm.ac.in/t/164277/517)

uv run https://raw.githubusercontent.com/sanand0/tools-in-data-science-public/tds-2025-01/project-1/evaluate.py

Installed 13 packages in 543ms

Traceback (most recent call last):

File “/tmp/evaluateF6zgG9.py”, line 20, in

from datagen import (

…&lt;9 lines&gt;…

)

ModuleNotFoundError: No module named ‘datagen’

I am getting this error when I try to run evaluate.py

when I run the evaluate.py by having datagen.py in same folder , it is running perfectly. But my doubt is only after task a1 runs the datagen.py will be downloaded into the /data folder right ?

@carlton @Saransh_Saini @Jivraj

Kindly help me with this issue
