---
chunk_id: discourse_topic_164277_post_369_00
source_url: https://discourse.onlinedegree.iitm.ac.in/t/164277/369
source_title: Project 1 - LLM-based Automation Agent - Discussion Thread [TDS Jan 2025]
content_type: discourse
tokens: 272
username: sarvan108
post_number: 369
topic_id: 164277
---

## Post #369 by sarvan108

**Direct Link**: [Post #369](https://discourse.onlinedegree.iitm.ac.in/t/164277/369)

How to resolve this?

sarvan108@SURIYA:/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro$ uv run app.py

Traceback (most recent call last):

File “/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro/app.py”, line 10, in

from fastapi import FastAPI

ModuleNotFoundError: No module named ‘fastapi’

sarvan108@SURIYA:/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro$ pip show fastapi

WARNING: Package(s) not found: fastapi

sarvan108@SURIYA:/mnt/c/Users/sarva/OneDrive/Documents/Knowledge/IIT Madras Datascience/tds_pro$ pip install fastapi

error: externally-managed-environment

× This environment is externally managed

╰─&gt; To install Python packages system-wide, try apt install

python3-xyz, where xyz is the package you are trying to

install.
